// GENERATED by scripts/gen-tokens.swift from design/tokens.css — DO NOT EDIT.
// Regenerate:  swift scripts/gen-tokens.swift design/tokens.css > Sources/UI/Tokens.swift
// CI fails if this file differs from a fresh run. Change tokens.css, not this file.

import AppKit
import SwiftUI

/// Colours from tokens.css. Display P3, light + dark via a dynamic `NSColor`.
/// `--nr-squircle` and `--nr-steel` exist only so the mark renders from tokens (manifest §2).
public enum NRColor {
    /// `--nr-bg` — #FCFCFB window · light #FDFCFB · dark #090907
    public static let bg = Color(nsColor: nr_dynamic(
        light: (0.9905, 0.9898, 0.9844),
        dark: (0.0367, 0.0358, 0.0299)))
    /// `--nr-surface` — #FFFFFF cards, bench chrome · light #FFFFFF · dark #121210
    public static let surface = Color(nsColor: nr_dynamic(
        light: (1.0000, 1.0000, 1.0000),
        dark: (0.0700, 0.0691, 0.0621)))
    /// `--nr-surface-2` — #F5F5F3 shelf, inspector · light #F5F5F3 · dark #1B1B19
    public static let surface2 = Color(nsColor: nr_dynamic(
        light: (0.9621, 0.9611, 0.9531),
        dark: (0.1054, 0.1044, 0.0970)))
    /// `--nr-hairline` — #E3E3E0 1px borders · light #DEDEDB · dark #2E2E2B
    public static let hairline = Color(nsColor: nr_dynamic(
        light: (0.8718, 0.8705, 0.8600),
        dark: (0.1811, 0.1799, 0.1699)))
    /// `--nr-fg` — #1D1D1B primary text · light #12120F · dark #EFEEEC
    public static let fg = Color(nsColor: nr_dynamic(
        light: (0.0704, 0.0692, 0.0604),
        dark: (0.9360, 0.9350, 0.9270)))
    /// `--nr-fg-2` — #66665F secondary · light #565552 · dark #9F9E9B
    public static let fg2 = Color(nsColor: nr_dynamic(
        light: (0.3364, 0.3347, 0.3214),
        dark: (0.6228, 0.6213, 0.6090)))
    /// `--nr-fg-3` — #93938B tertiary / placeholders · light #878682 · dark #696966
    public static let fg3 = Color(nsColor: nr_dynamic(
        light: (0.5281, 0.5264, 0.5120),
        dark: (0.4130, 0.4116, 0.4001)))
    /// `--relish-100` — #EEFBD0 active-jar tint, badge bg · light #E5FCC1 · dark #1D2F04
    public static let relish100 = Color(nsColor: nr_dynamic(
        light: (0.9159, 0.9854, 0.7800),
        dark: (0.1293, 0.1834, 0.0432)))
    /// `--relish-300` — #CDF48A hover on primary · #C4F16A
    public static let relish300 = Color(nsColor: nr_p3(0.8050, 0.9405, 0.4885))
    /// `--relish-500` — #93E413 THE relish. primary button, tab lip, seal glyph · #9CE700
    public static let relish500 = Color(nsColor: nr_p3(0.6763, 0.8962, 0.1538))
    /// `--relish-700` — #5C9A0B relish on light bg where contrast needs it · #5E9A00
    public static let relish700 = Color(nsColor: nr_p3(0.4232, 0.5995, 0.0552))
    /// `--relish-ink` — #1E3A12 text on relish-500 · light #122505 · dark #030C00
    public static let relishInk = Color(nsColor: nr_dynamic(
        light: (0.0876, 0.1439, 0.0368),
        dark: (0.0191, 0.0477, 0.0043)))
    /// `--nr-squircle` — #1F3F2E logo squircle. DO NOT use in UI · #14361D
    public static let squircle = Color(nsColor: nr_p3(0.1142, 0.2090, 0.1233))
    /// `--nr-steel` — #A9AFB6 logo gear. DO NOT use in UI · #9FA6AA
    public static let steel = Color(nsColor: nr_p3(0.6288, 0.6483, 0.6657))
    /// `--nr-danger` — #D9432E · #D73431
    public static let danger = Color(nsColor: nr_p3(0.7776, 0.2630, 0.2265))
    /// `--nr-warn` — #E4A72A shelf-life "sinking soon" · #ECAA0B
    public static let warn = Color(nsColor: nr_p3(0.8872, 0.6766, 0.2382))
    /// `--nr-focus` · alias
    public static let focus = relish500
}

/// Spacing and layout, in points. 4pt grid.
public enum NRSpace {
    /// `--sp-1`
    public static let sp1: CGFloat = 4
    /// `--sp-2`
    public static let sp2: CGFloat = 8
    /// `--sp-3`
    public static let sp3: CGFloat = 12
    /// `--sp-4`
    public static let sp4: CGFloat = 16
    /// `--sp-5`
    public static let sp5: CGFloat = 20
    /// `--sp-6`
    public static let sp6: CGFloat = 24
    /// `--sp-8`
    public static let sp8: CGFloat = 32
    /// `--sp-10`
    public static let sp10: CGFloat = 40
    /// `--sp-12`
    public static let sp12: CGFloat = 48
    /// `--shelf-w` — jar rail
    public static let shelfW: CGFloat = 56
    /// `--inspector-w`
    public static let inspectorW: CGFloat = 320
    /// `--tab-h`
    public static let tabH: CGFloat = 34
    /// `--lip-h` — relish tab lip, active tab only
    public static let lipH: CGFloat = 3
    /// `--hairline`
    public static let hairline: CGFloat = 1
}

/// Corner radii, in points, and the superellipse exponent.
public enum NRRadius {
    /// `--r-1` — controls
    public static let r1: CGFloat = 6
    /// `--r-2` — cards, tabs
    public static let r2: CGFloat = 10
    /// `--r-3` — panels, sheets
    public static let r3: CGFloat = 16
    /// `--r-jar` — jar objects
    public static let rJar: CGFloat = 14
    /// `--superellipse-n` — squircle exponent — mark, jar shoulders, app icon
    public static let superellipseN: Double = 5
}

/// Type. Sizes in points, line heights as multipliers. Weights 400/500/600 only (manifest §5).
public enum NRType {
    /// `--font-ui`
    public static let fontUI: Font.Design = .default
    /// `--font-mono`
    public static let fontMono: Font.Design = .monospaced
    /// `--font-hero` — site hero only. wght 800 / wdth 100 / opsz 96
    public static let fontHero: String = "Bricolage Grotesque"
    /// `--fs-xs`
    public static let fsXs: CGFloat = 11
    /// `--fs-sm`
    public static let fsSm: CGFloat = 12
    /// `--fs-md`
    public static let fsMd: CGFloat = 13
    /// `--fs-lg`
    public static let fsLg: CGFloat = 15
    /// `--fs-xl`
    public static let fsXl: CGFloat = 20
    /// `--fs-2xl`
    public static let fs2xl: CGFloat = 28
    /// `--fs-3xl`
    public static let fs3xl: CGFloat = 40
    /// `--lh-tight`
    public static let lhTight: CGFloat = 1.15
    /// `--lh-ui`
    public static let lhUI: CGFloat = 1.35
    /// `--lh-body`
    public static let lhBody: CGFloat = 1.5

    /// System font at a token size. `design` defaults to `fontUI`; pass `fontMono` for code and URLs.
    public static func font(_ size: CGFloat, weight: Font.Weight = .regular, design: Font.Design = fontUI) -> Font {
        .system(size: size, weight: weight, design: design)
    }
}

/// Motion. Durations in seconds, curves as `UnitCurve`. `seal` is the one drip (manifest §9).
public enum NRMotion {
    /// `--ease-out`
    public static let easeOut = UnitCurve.bezier(startControlPoint: UnitPoint(x: 0.16, y: 1.0), endControlPoint: UnitPoint(x: 0.3, y: 1.0))
    /// `--ease-jar` — jar drop / settle
    public static let easeJar = UnitCurve.bezier(startControlPoint: UnitPoint(x: 0.34, y: 1.4), endControlPoint: UnitPoint(x: 0.64, y: 1.0))
    /// `--t-fast`
    public static let fast: TimeInterval = 0.12
    /// `--t-base`
    public static let base: TimeInterval = 0.2
    /// `--t-seal`
    public static let seal: TimeInterval = 0.48

    /// An `Animation` from a token curve and a token duration.
    public static func animation(_ curve: UnitCurve = easeOut, duration: TimeInterval = base) -> Animation {
        .timingCurve(curve, duration: duration)
    }
}

/// Every token, by CSS name, for the Design Kit and tests. Generated alongside the enums.
public enum NRTokenCatalog {
    public struct ColorEntry: Sendable { public let css: String; public let swift: String; public let color: Color; public let note: String }
    public struct ScalarEntry: Sendable { public let css: String; public let swift: String; public let value: String }

    public static let colors: [ColorEntry] = [
        ColorEntry(css: "--nr-bg", swift: "bg", color: NRColor.bg, note: "light #FDFCFB · dark #090907"),
        ColorEntry(css: "--nr-surface", swift: "surface", color: NRColor.surface, note: "light #FFFFFF · dark #121210"),
        ColorEntry(css: "--nr-surface-2", swift: "surface2", color: NRColor.surface2, note: "light #F5F5F3 · dark #1B1B19"),
        ColorEntry(css: "--nr-hairline", swift: "hairline", color: NRColor.hairline, note: "light #DEDEDB · dark #2E2E2B"),
        ColorEntry(css: "--nr-fg", swift: "fg", color: NRColor.fg, note: "light #12120F · dark #EFEEEC"),
        ColorEntry(css: "--nr-fg-2", swift: "fg2", color: NRColor.fg2, note: "light #565552 · dark #9F9E9B"),
        ColorEntry(css: "--nr-fg-3", swift: "fg3", color: NRColor.fg3, note: "light #878682 · dark #696966"),
        ColorEntry(css: "--relish-100", swift: "relish100", color: NRColor.relish100, note: "light #E5FCC1 · dark #1D2F04"),
        ColorEntry(css: "--relish-300", swift: "relish300", color: NRColor.relish300, note: "#C4F16A"),
        ColorEntry(css: "--relish-500", swift: "relish500", color: NRColor.relish500, note: "#9CE700"),
        ColorEntry(css: "--relish-700", swift: "relish700", color: NRColor.relish700, note: "#5E9A00"),
        ColorEntry(css: "--relish-ink", swift: "relishInk", color: NRColor.relishInk, note: "light #122505 · dark #030C00"),
        ColorEntry(css: "--nr-squircle", swift: "squircle", color: NRColor.squircle, note: "#14361D"),
        ColorEntry(css: "--nr-steel", swift: "steel", color: NRColor.steel, note: "#9FA6AA"),
        ColorEntry(css: "--nr-danger", swift: "danger", color: NRColor.danger, note: "#D73431"),
        ColorEntry(css: "--nr-warn", swift: "warn", color: NRColor.warn, note: "#ECAA0B"),
        ColorEntry(css: "--nr-focus", swift: "focus", color: NRColor.focus, note: "= --relish-500"),
    ]
    public static let space: [ScalarEntry] = [
        ScalarEntry(css: "--sp-1", swift: "sp1", value: "4px"),
        ScalarEntry(css: "--sp-2", swift: "sp2", value: "8px"),
        ScalarEntry(css: "--sp-3", swift: "sp3", value: "12px"),
        ScalarEntry(css: "--sp-4", swift: "sp4", value: "16px"),
        ScalarEntry(css: "--sp-5", swift: "sp5", value: "20px"),
        ScalarEntry(css: "--sp-6", swift: "sp6", value: "24px"),
        ScalarEntry(css: "--sp-8", swift: "sp8", value: "32px"),
        ScalarEntry(css: "--sp-10", swift: "sp10", value: "40px"),
        ScalarEntry(css: "--sp-12", swift: "sp12", value: "48px"),
        ScalarEntry(css: "--shelf-w", swift: "shelfW", value: "56px"),
        ScalarEntry(css: "--inspector-w", swift: "inspectorW", value: "320px"),
        ScalarEntry(css: "--tab-h", swift: "tabH", value: "34px"),
        ScalarEntry(css: "--lip-h", swift: "lipH", value: "3px"),
        ScalarEntry(css: "--hairline", swift: "hairline", value: "1px"),
    ]
    public static let radius: [ScalarEntry] = [
        ScalarEntry(css: "--r-1", swift: "r1", value: "6px"),
        ScalarEntry(css: "--r-2", swift: "r2", value: "10px"),
        ScalarEntry(css: "--r-3", swift: "r3", value: "16px"),
        ScalarEntry(css: "--r-jar", swift: "rJar", value: "14px"),
        ScalarEntry(css: "--superellipse-n", swift: "superellipseN", value: "5"),
    ]
    public static let typography: [ScalarEntry] = [
        ScalarEntry(css: "--font-ui", swift: "fontUI", value: "-apple-system, \"SF Pro Text\", system-ui, sans-serif"),
        ScalarEntry(css: "--font-mono", swift: "fontMono", value: "\"SF Mono\", ui-monospace, Menlo, monospace"),
        ScalarEntry(css: "--font-hero", swift: "fontHero", value: "\"Bricolage Grotesque\", var(--font-ui)"),
        ScalarEntry(css: "--fs-xs", swift: "fsXs", value: "11px"),
        ScalarEntry(css: "--fs-sm", swift: "fsSm", value: "12px"),
        ScalarEntry(css: "--fs-md", swift: "fsMd", value: "13px"),
        ScalarEntry(css: "--fs-lg", swift: "fsLg", value: "15px"),
        ScalarEntry(css: "--fs-xl", swift: "fsXl", value: "20px"),
        ScalarEntry(css: "--fs-2xl", swift: "fs2xl", value: "28px"),
        ScalarEntry(css: "--fs-3xl", swift: "fs3xl", value: "40px"),
        ScalarEntry(css: "--lh-tight", swift: "lhTight", value: "1.15"),
        ScalarEntry(css: "--lh-ui", swift: "lhUI", value: "1.35"),
        ScalarEntry(css: "--lh-body", swift: "lhBody", value: "1.5"),
    ]
    public static let motion: [ScalarEntry] = [
        ScalarEntry(css: "--ease-out", swift: "easeOut", value: "cubic-bezier(0.16, 1, 0.3, 1)"),
        ScalarEntry(css: "--ease-jar", swift: "easeJar", value: "cubic-bezier(0.34, 1.4, 0.64, 1)"),
        ScalarEntry(css: "--t-fast", swift: "fast", value: "120ms"),
        ScalarEntry(css: "--t-base", swift: "base", value: "200ms"),
        ScalarEntry(css: "--t-seal", swift: "seal", value: "480ms"),
    ]

    /// Every CSS custom property this file was generated from — one static each.
    public static let allCSSNames: [String] = [
        "--nr-bg",
        "--nr-surface",
        "--nr-surface-2",
        "--nr-hairline",
        "--nr-fg",
        "--nr-fg-2",
        "--nr-fg-3",
        "--relish-100",
        "--relish-300",
        "--relish-500",
        "--relish-700",
        "--relish-ink",
        "--nr-squircle",
        "--nr-steel",
        "--nr-danger",
        "--nr-warn",
        "--nr-focus",
        "--sp-1",
        "--sp-2",
        "--sp-3",
        "--sp-4",
        "--sp-5",
        "--sp-6",
        "--sp-8",
        "--sp-10",
        "--sp-12",
        "--shelf-w",
        "--inspector-w",
        "--tab-h",
        "--lip-h",
        "--hairline",
        "--r-1",
        "--r-2",
        "--r-3",
        "--r-jar",
        "--superellipse-n",
        "--font-ui",
        "--font-mono",
        "--font-hero",
        "--fs-xs",
        "--fs-sm",
        "--fs-md",
        "--fs-lg",
        "--fs-xl",
        "--fs-2xl",
        "--fs-3xl",
        "--lh-tight",
        "--lh-ui",
        "--lh-body",
        "--ease-out",
        "--ease-jar",
        "--t-fast",
        "--t-base",
        "--t-seal",
    ]
}

// MARK: - Helpers (generated once, not tokens)

/// A Display P3 colour that is the same in light and dark.
private func nr_p3(_ r: Double, _ g: Double, _ b: Double) -> NSColor {
    NSColor(displayP3Red: r, green: g, blue: b, alpha: 1)
}

/// A Display P3 colour that resolves against the drawing appearance: light for Aqua, dark for Dark Aqua.
private func nr_dynamic(light: (Double, Double, Double), dark: (Double, Double, Double)) -> NSColor {
    NSColor(name: nil) { appearance in
        let isDark = appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
        let c = isDark ? dark : light
        return NSColor(displayP3Red: c.0, green: c.1, blue: c.2, alpha: 1)
    }
}
