// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// A set of Items handled together — one Recipe run, one export, one Seal.
public struct Batch: Codable, Identifiable, Hashable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "batches"

    /// The MSON `_id`.
    public var id: String
    /// `createdAt` · date · read-only
    public let createdAt: Date
    /// `finishedAt` · date
    public var finishedAt: Date?
    /// `status` · string
    public var status: String
    /// `recipe` → Recipe. The foreign key; fetch the record with `recipe(_:)`.
    public var recipeId: String?

    public init(
        id: String = UUID().uuidString,
        createdAt: Date = Date(),
        finishedAt: Date? = nil,
        status: String = "queued",
        recipeId: String? = nil
    ) {
        self.id = id
        self.createdAt = createdAt
        self.finishedAt = finishedAt
        self.status = status
        self.recipeId = recipeId
    }

    public enum Columns {
        public static let id = Column("id")
        public static let createdAt = Column("createdAt")
        public static let finishedAt = Column("finishedAt")
        public static let status = Column("status")
        public static let recipeId = Column("recipeId")
    }

    // MARK: Associations

    public static let recipe = belongsTo(Recipe.self, key: "recipe", using: ForeignKey(["recipeId"]))
    public func recipe(_ db: Database) throws -> Recipe? {
        guard let recipeId else { return nil }
        return try Recipe.fetchOne(db, key: recipeId)
    }

    public static let items = hasMany(Item.self, key: "items", using: ForeignKey(["batchId"]))
    public func items(_ db: Database) throws -> [Item] {
        try Item.filter(Item.Columns.batchId == id).fetchAll(db)
    }

    // MARK: Events

    /// `onFinished` — an `AsyncStream<Batch>`; also posted as `Notification.Name("NetRelish.Batch.onFinished")`.
    public static let onFinished = PantryEvent<Batch>("NetRelish.Batch.onFinished")
}
