// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// Everything the user saves. One table. kind is the discriminator.
public struct Item: Codable, Identifiable, Hashable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "items"

    /// The MSON `_id`.
    public var id: String
    /// `body` · string
    public var body: String?
    /// `createdAt` · date · read-only
    public let createdAt: Date
    /// `domain` · string
    public var domain: String?
    /// `excerpt` · string
    public var excerpt: String?
    /// `kind` · ItemKind
    public var kind: ItemKind
    /// `meta` · object
    public var meta: Data?
    /// `sealedAt` · date
    public var sealedAt: Date?
    /// `snapshotPath` · string
    public var snapshotPath: String?
    /// `source` · CaptureSource · read-only
    public let source: CaptureSource
    /// `state` · ItemState
    public var state: ItemState
    /// `title` · string
    public var title: String
    /// `updatedAt` · date
    public var updatedAt: Date
    /// `url` · string
    public var url: String?
    /// `batch` → Batch. The foreign key; fetch the record with `batch(_:)`.
    public var batchId: String?
    /// `jar` → Jar. The foreign key; fetch the record with `jar(_:)`.
    public var jarId: String?

    public init(
        id: String = UUID().uuidString,
        body: String? = nil,
        createdAt: Date = Date(),
        domain: String? = nil,
        excerpt: String? = nil,
        kind: ItemKind = .page,
        meta: Data? = nil,
        sealedAt: Date? = nil,
        snapshotPath: String? = nil,
        source: CaptureSource = .browse,
        state: ItemState = .brined,
        title: String = "",
        updatedAt: Date = Date(),
        url: String? = nil,
        batchId: String? = nil,
        jarId: String? = nil
    ) {
        self.id = id
        self.body = body
        self.createdAt = createdAt
        self.domain = domain
        self.excerpt = excerpt
        self.kind = kind
        self.meta = meta
        self.sealedAt = sealedAt
        self.snapshotPath = snapshotPath
        self.source = source
        self.state = state
        self.title = title
        self.updatedAt = updatedAt
        self.url = url
        self.batchId = batchId
        self.jarId = jarId
    }

    public enum Columns {
        public static let id = Column("id")
        public static let body = Column("body")
        public static let createdAt = Column("createdAt")
        public static let domain = Column("domain")
        public static let excerpt = Column("excerpt")
        public static let kind = Column("kind")
        public static let meta = Column("meta")
        public static let sealedAt = Column("sealedAt")
        public static let snapshotPath = Column("snapshotPath")
        public static let source = Column("source")
        public static let state = Column("state")
        public static let title = Column("title")
        public static let updatedAt = Column("updatedAt")
        public static let url = Column("url")
        public static let batchId = Column("batchId")
        public static let jarId = Column("jarId")
    }

    // MARK: Associations

    public static let batch = belongsTo(Batch.self, key: "batch", using: ForeignKey(["batchId"]))
    public func batch(_ db: Database) throws -> Batch? {
        guard let batchId else { return nil }
        return try Batch.fetchOne(db, key: batchId)
    }

    public static let jar = belongsTo(Jar.self, key: "jar", using: ForeignKey(["jarId"]))
    public func jar(_ db: Database) throws -> Jar? {
        guard let jarId else { return nil }
        return try Jar.fetchOne(db, key: jarId)
    }

    /// Many-to-many through `items_labels`.
    public static let labelsPivot = hasMany(Table("items_labels"), using: ForeignKey(["itemId"]))
    public static let labels = hasMany(Label.self, through: labelsPivot, using: Table("items_labels").belongsTo(Label.self, using: ForeignKey(["labelId"])))
    public func labels(_ db: Database) throws -> [Label] {
        try Label.fetchAll(db, sql: "SELECT t.* FROM labels t JOIN items_labels j ON j.labelId = t.id WHERE j.itemId = ?", arguments: [id])
    }
    public func setLabels(_ ids: [String], _ db: Database) throws {
        try db.execute(sql: "DELETE FROM items_labels WHERE itemId = ?", arguments: [id])
        for other in ids { try db.execute(sql: "INSERT INTO items_labels (itemId, labelId) VALUES (?, ?)", arguments: [id, other]) }
    }

    // MARK: Events

    /// `onSealed` — an `AsyncStream<Item>`; also posted as `Notification.Name("NetRelish.Item.onSealed")`.
    public static let onSealed = PantryEvent<Item>("NetRelish.Item.onSealed")
}

/// The methods the diagram gives `Item`. Bodies live in Behaviors/Item+Behavior.swift
/// and mirror the JavaScript quoted here. `Item` must conform, so a missing body is a compile error.
public protocol ItemMethods {

    /// ```javascript
    /// function seal() {
    ///   if (this.state() === 'sealed') return this;
    ///   const now = new Date();
    ///   this.state('sealed');
    ///   this.sealedAt(now);
    ///   this.updatedAt(now);
    ///   this.onSealed(this);
    ///   return this;
    /// }
    /// ```
    mutating func seal(_ db: Database) throws -> Item
}
