// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// A project, and a profile. Has a shelf life. Where Brine goes once sorted.
public struct Jar: Codable, Identifiable, Hashable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "jars"

    /// The MSON `_id`.
    public var id: String
    /// `glyph` · string
    public var glyph: String?
    /// `isPinned` · boolean
    public var isPinned: Bool?
    /// `name` · string
    public var name: String
    /// `shelfLifeDays` · number
    public var shelfLifeDays: Double?
    /// `sortOrder` · number
    public var sortOrder: Double?
    /// `tint` · string
    public var tint: String?
    /// `defaultRecipe` → Recipe. The foreign key; fetch the record with `defaultRecipe(_:)`.
    public var defaultRecipeId: String?

    public init(
        id: String = UUID().uuidString,
        glyph: String? = nil,
        isPinned: Bool? = nil,
        name: String = "",
        shelfLifeDays: Double? = nil,
        sortOrder: Double? = nil,
        tint: String? = nil,
        defaultRecipeId: String? = nil
    ) {
        self.id = id
        self.glyph = glyph
        self.isPinned = isPinned
        self.name = name
        self.shelfLifeDays = shelfLifeDays
        self.sortOrder = sortOrder
        self.tint = tint
        self.defaultRecipeId = defaultRecipeId
    }

    public enum Columns {
        public static let id = Column("id")
        public static let glyph = Column("glyph")
        public static let isPinned = Column("isPinned")
        public static let name = Column("name")
        public static let shelfLifeDays = Column("shelfLifeDays")
        public static let sortOrder = Column("sortOrder")
        public static let tint = Column("tint")
        public static let defaultRecipeId = Column("defaultRecipeId")
    }

    // MARK: Associations

    public static let defaultRecipe = belongsTo(Recipe.self, key: "defaultRecipe", using: ForeignKey(["defaultRecipeId"]))
    public func defaultRecipe(_ db: Database) throws -> Recipe? {
        guard let defaultRecipeId else { return nil }
        return try Recipe.fetchOne(db, key: defaultRecipeId)
    }

    public static let items = hasMany(Item.self, key: "items", using: ForeignKey(["jarId"]))
    public func items(_ db: Database) throws -> [Item] {
        try Item.filter(Item.Columns.jarId == id).fetchAll(db)
    }

    public static let tabs = hasMany(Tab.self, key: "tabs", using: ForeignKey(["jarId"]))
    public func tabs(_ db: Database) throws -> [Tab] {
        try Tab.filter(Tab.Columns.jarId == id).fetchAll(db)
    }

    // MARK: Events

    /// `onItemDropped` — an `AsyncStream<Item>`; also posted as `Notification.Name("NetRelish.Jar.onItemDropped")`.
    public static let onItemDropped = PantryEvent<Item>("NetRelish.Jar.onItemDropped")
}
