// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// Flat tag. No hierarchy — Jars do that job.
public struct Label: Codable, Identifiable, Hashable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "labels"

    /// The MSON `_id`.
    public var id: String
    /// `name` · string
    public var name: String
    /// `tint` · string
    public var tint: String?

    public init(
        id: String = UUID().uuidString,
        name: String = "",
        tint: String? = nil
    ) {
        self.id = id
        self.name = name
        self.tint = tint
    }

    public enum Columns {
        public static let id = Column("id")
        public static let name = Column("name")
        public static let tint = Column("tint")
    }

    // MARK: Associations

    /// Many-to-many through `items_labels`.
    public static let itemsPivot = hasMany(Table("items_labels"), using: ForeignKey(["labelId"]))
    public static let items = hasMany(Item.self, through: itemsPivot, using: Table("items_labels").belongsTo(Item.self, using: ForeignKey(["itemId"])))
    public func items(_ db: Database) throws -> [Item] {
        try Item.fetchAll(db, sql: "SELECT t.* FROM items t JOIN items_labels j ON j.itemId = t.id WHERE j.labelId = ?", arguments: [id])
    }
    public func setItems(_ ids: [String], _ db: Database) throws {
        try db.execute(sql: "DELETE FROM items_labels WHERE labelId = ?", arguments: [id])
        for other in ids { try db.execute(sql: "INSERT INTO items_labels (labelId, itemId) VALUES (?, ?)", arguments: [id, other]) }
    }
}
