// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// The workbench. Root of the system.
public struct NetRelish: Codable, Identifiable, Hashable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "netrelish"

    /// The MSON `_id`.
    public var id: String
    /// `tagline` · string · read-only
    public let tagline: String?
    /// `activeJar` → Jar. The foreign key; fetch the record with `activeJar(_:)`.
    public var activeJarId: String?

    /// The one row. `start` creates it if it is missing.
    public static let singletonId = "pantry"

    public init(
        id: String = UUID().uuidString,
        tagline: String? = nil,
        activeJarId: String? = nil
    ) {
        self.id = id
        self.tagline = tagline
        self.activeJarId = activeJarId
    }

    public enum Columns {
        public static let id = Column("id")
        public static let tagline = Column("tagline")
        public static let activeJarId = Column("activeJarId")
    }

    // MARK: Associations

    public static let activeJar = belongsTo(Jar.self, key: "activeJar", using: ForeignKey(["activeJarId"]))
    public func activeJar(_ db: Database) throws -> Jar? {
        guard let activeJarId else { return nil }
        return try Jar.fetchOne(db, key: activeJarId)
    }

    /// `brine` — all Item rows, except that Brine is a query: `jar == nil && state == .brined`.
    public func brine(_ db: Database) throws -> [Item] {
        try Item.filter(Item.Columns.jarId == nil && Item.Columns.state == ItemState.brined).order(Item.Columns.updatedAt.desc).fetchAll(db)
    }

    /// `jars` — all Jar rows.
    public func jars(_ db: Database) throws -> [Jar] {
        try Jar.order(Jar.Columns.sortOrder).fetchAll(db)
    }

    /// `labels` — all Label rows.
    public func labels(_ db: Database) throws -> [Label] {
        try Label.fetchAll(db)
    }

    /// `recipes` — all Recipe rows.
    public func recipes(_ db: Database) throws -> [Recipe] {
        try Recipe.fetchAll(db)
    }

    // MARK: Events

    /// `onCapture` — an `AsyncStream<Item>`; also posted as `Notification.Name("NetRelish.NetRelish.onCapture")`.
    public static let onCapture = PantryEvent<Item>("NetRelish.NetRelish.onCapture")

    /// `onSeal` — an `AsyncStream<Item>`; also posted as `Notification.Name("NetRelish.NetRelish.onSeal")`.
    public static let onSeal = PantryEvent<Item>("NetRelish.NetRelish.onSeal")
}

/// The methods the diagram gives `NetRelish`. Bodies live in Behaviors/NetRelish+Behavior.swift
/// and mirror the JavaScript quoted here. `NetRelish` must conform, so a missing body is a compile error.
public protocol NetRelishMethods {

    /// ```javascript
    /// function capture(url) {
    ///   const Item = this.require('Item');
    ///   const now = new Date();
    ///   const item = new Item({
    ///     kind: 'page',
    ///     state: 'brined',
    ///     title: url,
    ///     url: url,
    ///     domain: new URL(url).hostname,
    ///     source: 'browse',
    ///     createdAt: now,
    ///     updatedAt: now
    ///   });
    ///   this.brine().push(item);
    ///   this.onCapture(item);
    ///   return item;
    /// }
    /// ```
    func capture(_ db: Database, url: String) throws -> Item

    /// ```javascript
    /// function runRecipe(recipe, items) {
    ///   return recipe.run(items);
    /// }
    /// ```
    func runRecipe(_ db: Database, recipe: Recipe, items: [Item]) throws -> Batch

    /// ```javascript
    /// function seal(item) {
    ///   item.seal();
    ///   this.onSeal(item);
    ///   return item;
    /// }
    /// ```
    func seal(_ db: Database, item: Item) throws -> Item
}
