// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// A repeatable workflow. Ordered Steps, one Trigger. Every Recipe is an App Intent.
public struct Recipe: Codable, Identifiable, Hashable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "recipes"

    /// The MSON `_id`.
    public var id: String
    /// `isShortcutExposed` · boolean
    public var isShortcutExposed: Bool?
    /// `lastRunAt` · date
    public var lastRunAt: Date?
    /// `name` · string
    public var name: String
    /// `schedule` · string
    public var schedule: String?
    /// `trigger` · RecipeTrigger
    public var trigger: RecipeTrigger

    public init(
        id: String = UUID().uuidString,
        isShortcutExposed: Bool? = nil,
        lastRunAt: Date? = nil,
        name: String = "",
        schedule: String? = nil,
        trigger: RecipeTrigger = .manual
    ) {
        self.id = id
        self.isShortcutExposed = isShortcutExposed
        self.lastRunAt = lastRunAt
        self.name = name
        self.schedule = schedule
        self.trigger = trigger
    }

    public enum Columns {
        public static let id = Column("id")
        public static let isShortcutExposed = Column("isShortcutExposed")
        public static let lastRunAt = Column("lastRunAt")
        public static let name = Column("name")
        public static let schedule = Column("schedule")
        public static let trigger = Column("trigger")
    }

    // MARK: Associations

    public static let steps = hasMany(Step.self, key: "steps", using: ForeignKey(["recipeId"]))
    public func steps(_ db: Database) throws -> [Step] {
        try Step.filter(Step.Columns.recipeId == id).fetchAll(db)
    }

    // MARK: Events

    /// `onRunFinished` — an `AsyncStream<Batch>`; also posted as `Notification.Name("NetRelish.Recipe.onRunFinished")`.
    public static let onRunFinished = PantryEvent<Batch>("NetRelish.Recipe.onRunFinished")
}

/// The methods the diagram gives `Recipe`. Bodies live in Behaviors/Recipe+Behavior.swift
/// and mirror the JavaScript quoted here. `Recipe` must conform, so a missing body is a compile error.
public protocol RecipeMethods {

    /// ```javascript
    /// function run(items) {
    ///   const Batch = this.require('Batch');
    ///   const batch = new Batch({ status: 'running', createdAt: new Date(), recipe: this, items: items });
    ///   const steps = this.steps().sort((a, b) => a.order() - b.order());
    ///   for (const item of items) {
    ///     for (const step of steps) {
    ///       try {
    ///         step.execute(item);
    ///       } catch (e) {
    ///         if (step.haltOnFail()) {
    ///           batch.status('failed');
    ///           batch.finishedAt(new Date());
    ///           this.onRunFinished(batch);
    ///           return batch;
    ///         }
    ///       }
    ///     }
    ///   }
    ///   batch.status('done');
    ///   batch.finishedAt(new Date());
    ///   this.lastRunAt(new Date());
    ///   this.onRunFinished(batch);
    ///   return batch;
    /// }
    /// ```
    mutating func run(_ db: Database, items: [Item]) throws -> Batch
}
