// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// Creates every table, join table and index the diagram implies. Called by Migrations/V1.
public enum PantrySchema {
    /// Table names, in creation order (referenced tables first).
    public static let tables: [String] = ["labels", "recipes", "batches", "jars", "items", "netrelish", "steps", "tabs"]

    public static func create(_ db: Database) throws {
        try db.create(table: "labels") { t in
            t.primaryKey("id", .text)
            t.column("name", .text).notNull()
            t.column("tint", .text)
        }
        try db.create(table: "recipes") { t in
            t.primaryKey("id", .text)
            t.column("isShortcutExposed", .boolean)
            t.column("lastRunAt", .datetime)
            t.column("name", .text).notNull()
            t.column("schedule", .text)
            t.column("trigger", .text).notNull()
        }
        try db.create(table: "batches") { t in
            t.primaryKey("id", .text)
            t.column("createdAt", .datetime).notNull()
            t.column("finishedAt", .datetime)
            t.column("status", .text).notNull()
            t.belongsTo("recipe", inTable: "recipes", onDelete: .setNull)
        }
        try db.create(table: "jars") { t in
            t.primaryKey("id", .text)
            t.column("glyph", .text)
            t.column("isPinned", .boolean)
            t.column("name", .text).notNull()
            t.column("shelfLifeDays", .double)
            t.column("sortOrder", .double)
            t.column("tint", .text)
            t.belongsTo("defaultRecipe", inTable: "recipes", onDelete: .setNull)
        }
        try db.create(table: "items") { t in
            t.primaryKey("id", .text)
            t.column("body", .text)
            t.column("createdAt", .datetime).notNull()
            t.column("domain", .text)
            t.column("excerpt", .text)
            t.column("kind", .text).notNull()
            t.column("meta", .blob)
            t.column("sealedAt", .datetime)
            t.column("snapshotPath", .text)
            t.column("source", .text).notNull()
            t.column("state", .text).notNull()
            t.column("title", .text).notNull()
            t.column("updatedAt", .datetime).notNull()
            t.column("url", .text)
            t.belongsTo("batch", inTable: "batches", onDelete: .setNull)
            t.belongsTo("jar", inTable: "jars", onDelete: .setNull)
        }
        try db.create(table: "netrelish") { t in
            t.primaryKey("id", .text)
            t.column("tagline", .text)
            t.belongsTo("activeJar", inTable: "jars", onDelete: .setNull)
        }
        try db.create(table: "steps") { t in
            t.primaryKey("id", .text)
            t.column("action", .text).notNull()
            t.column("haltOnFail", .boolean)
            t.column("order", .double).notNull()
            t.column("params", .blob)
            t.belongsTo("recipe", inTable: "recipes", onDelete: .setNull)
        }
        try db.create(table: "tabs") { t in
            t.primaryKey("id", .text)
            t.column("interactionState", .blob)
            t.column("isPinned", .boolean).notNull()
            t.column("openedAt", .datetime).notNull()
            t.column("sortOrder", .double).notNull()
            t.column("title", .text)
            t.column("touchedAt", .datetime).notNull()
            t.column("url", .text)
            t.belongsTo("jar", inTable: "jars", onDelete: .setNull)
        }
        try db.create(table: "items_labels") { t in
            t.belongsTo("item", inTable: "items", onDelete: .cascade).notNull()
            t.belongsTo("label", inTable: "labels", onDelete: .cascade).notNull()
            t.primaryKey(["itemId", "labelId"])
        }
        try db.create(indexOn: "recipes", columns: ["trigger"])
        try db.create(indexOn: "batches", columns: ["createdAt"])
        try db.create(indexOn: "items", columns: ["createdAt"])
        try db.create(indexOn: "items", columns: ["kind"])
        try db.create(indexOn: "items", columns: ["source"])
        try db.create(indexOn: "items", columns: ["state"])
        try db.create(indexOn: "items", columns: ["updatedAt"])
        try db.create(indexOn: "items", columns: ["url"])
        try db.create(indexOn: "steps", columns: ["action"])
        try db.create(indexOn: "tabs", columns: ["url"])
    }
}
