// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// The bundle's components — the rows a fresh Pantry starts with. Applied by the first migration.
public enum PantrySeed {
    public static func apply(_ db: Database) throws {
        try db.execute(sql: "INSERT OR IGNORE INTO jars (id, glyph, isPinned, name, shelfLifeDays, sortOrder) VALUES (?, ?, ?, ?, ?, ?)", arguments: ["read-later", "nr-jar", true, "Read Later", 3.0, 0.0])
        try db.execute(sql: "INSERT OR IGNORE INTO jars (id, glyph, isPinned, name, shelfLifeDays, sortOrder) VALUES (?, ?, ?, ?, ?, ?)", arguments: ["reference", "nr-jar", false, "Reference", 7.0, 1.0])
        try db.execute(sql: "INSERT OR IGNORE INTO recipes (id, isShortcutExposed, name, trigger) VALUES (?, ?, ?, ?)", arguments: ["seal-summarize", true, "Seal & Summarize", "onSeal"])
        // NetRelish.jars = ["read-later", "reference"] — Jar rows seeded above
        // NetRelish.recipes = ["seal-summarize"] — Recipe rows seeded above
        try db.execute(sql: "INSERT OR IGNORE INTO netrelish (id, activeJarId) VALUES (?, ?)", arguments: ["pantry", "read-later"])
    }
}
