// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// One atomic unit of a Recipe. A function of Item -> Item.
public struct Step: Codable, Identifiable, Hashable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "steps"

    /// The MSON `_id`.
    public var id: String
    /// `action` · StepAction
    public var action: StepAction
    /// `haltOnFail` · boolean
    public var haltOnFail: Bool?
    /// `order` · number
    public var order: Double
    /// `params` · object
    public var params: Data?
    /// `recipe` → Recipe. The foreign key; fetch the record with `recipe(_:)`.
    public var recipeId: String?

    public init(
        id: String = UUID().uuidString,
        action: StepAction = .addLabel,
        haltOnFail: Bool? = nil,
        order: Double = 0.0,
        params: Data? = nil,
        recipeId: String? = nil
    ) {
        self.id = id
        self.action = action
        self.haltOnFail = haltOnFail
        self.order = order
        self.params = params
        self.recipeId = recipeId
    }

    public enum Columns {
        public static let id = Column("id")
        public static let action = Column("action")
        public static let haltOnFail = Column("haltOnFail")
        public static let order = Column("order")
        public static let params = Column("params")
        public static let recipeId = Column("recipeId")
    }

    // MARK: Associations

    public static let recipe = belongsTo(Recipe.self, key: "recipe", using: ForeignKey(["recipeId"]))
    public func recipe(_ db: Database) throws -> Recipe? {
        guard let recipeId else { return nil }
        return try Recipe.fetchOne(db, key: recipeId)
    }
}

/// The methods the diagram gives `Step`. Bodies live in Behaviors/Step+Behavior.swift
/// and mirror the JavaScript quoted here. `Step` must conform, so a missing body is a compile error.
public protocol StepMethods {

    /// ```javascript
    /// function execute(item) {
    ///   const params = this.params() || {};
    ///   switch (this.action()) {
    ///     case 'addLabel': {
    ///       const labels = item.labels();
    ///       if (params.label && !labels.includes(params.label)) labels.push(params.label);
    ///       item.labels(labels);
    ///       break;
    ///     }
    ///     case 'removeLabel': {
    ///       item.labels(item.labels().filter(l => l !== params.label));
    ///       break;
    ///     }
    ///     case 'moveToJar': {
    ///       item.jar(params.jar);
    ///       item.state('jarred');
    ///       break;
    ///     }
    ///     case 'seal': {
    ///       item.seal();
    ///       break;
    ///     }
    ///     default: {
    ///       // summarize, extractLinks, extractTasks, ocrImage, exportMarkdown,
    ///       // exportPDF, runShortcut, notify: performed on-device by the app,
    ///       // reading the sealed snapshot only. Nothing to model here.
    ///       break;
    ///     }
    ///   }
    ///   item.updatedAt(new Date());
    ///   return item;
    /// }
    /// ```
    mutating func execute(_ db: Database, item: Item) throws -> Item
}
