// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// An open pane on the Bench. Belongs to a jar; sinks into Brine past the jar's shelf life unless pinned.
public struct Tab: Codable, Identifiable, Hashable, Sendable, FetchableRecord, MutablePersistableRecord {
    public static let databaseTableName = "tabs"

    /// The MSON `_id`.
    public var id: String
    /// `interactionState` · object
    public var interactionState: Data?
    /// `isPinned` · boolean
    public var isPinned: Bool
    /// `openedAt` · date · read-only
    public let openedAt: Date
    /// `sortOrder` · number
    public var sortOrder: Double
    /// `title` · string
    public var title: String?
    /// `touchedAt` · date
    public var touchedAt: Date
    /// `url` · string
    public var url: String?
    /// `jar` → Jar. The foreign key; fetch the record with `jar(_:)`.
    public var jarId: String?

    public init(
        id: String = UUID().uuidString,
        interactionState: Data? = nil,
        isPinned: Bool = false,
        openedAt: Date = Date(),
        sortOrder: Double = 0.0,
        title: String? = nil,
        touchedAt: Date = Date(),
        url: String? = nil,
        jarId: String? = nil
    ) {
        self.id = id
        self.interactionState = interactionState
        self.isPinned = isPinned
        self.openedAt = openedAt
        self.sortOrder = sortOrder
        self.title = title
        self.touchedAt = touchedAt
        self.url = url
        self.jarId = jarId
    }

    public enum Columns {
        public static let id = Column("id")
        public static let interactionState = Column("interactionState")
        public static let isPinned = Column("isPinned")
        public static let openedAt = Column("openedAt")
        public static let sortOrder = Column("sortOrder")
        public static let title = Column("title")
        public static let touchedAt = Column("touchedAt")
        public static let url = Column("url")
        public static let jarId = Column("jarId")
    }

    // MARK: Associations

    public static let jar = belongsTo(Jar.self, key: "jar", using: ForeignKey(["jarId"]))
    public func jar(_ db: Database) throws -> Jar? {
        guard let jarId else { return nil }
        return try Jar.fetchOne(db, key: jarId)
    }

    // MARK: Events

    /// `onSunk` — an `AsyncStream<Item>`; also posted as `Notification.Name("NetRelish.Tab.onSunk")`.
    public static let onSunk = PantryEvent<Item>("NetRelish.Tab.onSunk")
}

/// The methods the diagram gives `Tab`. Bodies live in Behaviors/Tab+Behavior.swift
/// and mirror the JavaScript quoted here. `Tab` must conform, so a missing body is a compile error.
public protocol TabMethods {

    /// ```javascript
    /// function sink() {
    ///   const Item = this.require('Item');
    ///   const now = new Date();
    ///   const item = new Item({
    ///     kind: 'page',
    ///     state: 'brined',
    ///     title: this.title(),
    ///     url: this.url(),
    ///     domain: this.url() ? new URL(this.url()).hostname : '',
    ///     source: 'browse',
    ///     createdAt: now,
    ///     updatedAt: now,
    ///     meta: { interactionState: this.interactionState(), originJar: this.jar() ? this.jar().id() : null }
    ///   });
    ///   this.onSunk(item);
    ///   this.destroy();
    ///   return item;
    /// }
    /// ```
    mutating func sink(_ db: Database) throws -> Item
}
