// GENERATED by scripts/gen-pantry.swift from design/NetRelish.json — DO NOT EDIT.
// Regenerate:  swift scripts/gen-pantry.swift design/NetRelish.json Sources/Pantry/Models
// CI fails if this file differs from a fresh run. Change the diagram, not this file.
import Foundation
import GRDB

/// How an Item entered the Pantry.
public enum CaptureSource: String, Codable, CaseIterable, Sendable, DatabaseValueConvertible {
    case browse
    case shareExtension
    case clipboard
    case drop
    case shortcut
    case recipe
}

/// What an Item is. The single discriminator.
public enum ItemKind: String, Codable, CaseIterable, Sendable, DatabaseValueConvertible {
    case page
    case note
    case task
    case file
    case message
    case clip
}

/// Where an Item is in its life. Seal is the only one-way move.
public enum ItemState: String, Codable, CaseIterable, Sendable, DatabaseValueConvertible {
    case brined
    case jarred
    case sealed
}

/// What starts a Recipe.
public enum RecipeTrigger: String, Codable, CaseIterable, Sendable, DatabaseValueConvertible {
    case manual
    case onCapture
    case onSeal
    case onJarDrop
    case scheduled
}

/// The atomic operations a Step can perform on an Item.
public enum StepAction: String, Codable, CaseIterable, Sendable, DatabaseValueConvertible {
    case addLabel
    case removeLabel
    case moveToJar
    case seal
    case summarize
    case extractLinks
    case extractTasks
    case ocrImage
    case exportMarkdown
    case exportPDF
    case runShortcut
    case notify
}
