#!/usr/bin/env swift
// gen-symbols.swift — reads design/symbols.svg and both logos, writes Sources/UI/Symbols.swift.
//
//   swift scripts/gen-symbols.swift design/symbols.svg design/logo.svg design/logo-cog.svg > Sources/UI/Symbols.swift
//
// Each `<symbol>` becomes a standalone SVG document embedded as a string and loaded
// through `NSImage(data:)` as a *template* image, so `currentColor` is whatever tint
// the caller sets. The logos are embedded byte-for-byte and loaded *full colour* —
// a template would recolour the mark, which the manifest forbids (§2).
//
// The seven ids from manifest §7 are required, in that order. Anything else in the
// file is an error: no custom icons beyond §7.

import Foundation

let args = Array(CommandLine.arguments.dropFirst())
guard args.count == 3 else {
    FileHandle.standardError.write("usage: gen-symbols.swift <symbols.svg> <logo.svg> <logo-cog.svg>\n".data(using: .utf8)!)
    exit(2)
}
func fail(_ msg: String) -> Never {
    FileHandle.standardError.write("gen-symbols: error: \(msg)\n".data(using: .utf8)!)
    exit(1)
}
func read(_ path: String) -> String {
    guard let s = try? String(contentsOfFile: path, encoding: .utf8) else { fail("cannot read \(path)") }
    return s
}

let symbolsSVG = read(args[0])
let logoSVG = read(args[1])
let cogSVG = read(args[2])

// MARK: - Parse <symbol> elements

struct Sym { let id: String; let attrs: String; let body: String; let width: Double; let height: Double }

let symbolRE = try! NSRegularExpression(pattern: #"<symbol\s+([^>]*)>(.*?)</symbol>"#, options: [.dotMatchesLineSeparators])
let attrRE = try! NSRegularExpression(pattern: #"([a-zA-Z:-]+)="([^"]*)""#)

var symbols: [Sym] = []
for m in symbolRE.matches(in: symbolsSVG, range: NSRange(symbolsSVG.startIndex..., in: symbolsSVG)) {
    let attrText = String(symbolsSVG[Range(m.range(at: 1), in: symbolsSVG)!])
    let body = String(symbolsSVG[Range(m.range(at: 2), in: symbolsSVG)!])
    var attrs: [String: String] = [:]
    for a in attrRE.matches(in: attrText, range: NSRange(attrText.startIndex..., in: attrText)) {
        attrs[String(attrText[Range(a.range(at: 1), in: attrText)!])] = String(attrText[Range(a.range(at: 2), in: attrText)!])
    }
    guard let id = attrs["id"] else { fail("a <symbol> has no id") }
    guard let vb = attrs["viewBox"] else { fail("#\(id) has no viewBox") }
    let parts = vb.split(separator: " ").compactMap { Double($0) }
    guard parts.count == 4 else { fail("#\(id): bad viewBox `\(vb)`") }
    // Carry every attribute except id through to the standalone <svg>.
    let passthrough = attrs.filter { $0.key != "id" }.sorted { $0.key < $1.key }
        .map { "\($0.key)=\"\($0.value)\"" }.joined(separator: " ")
    symbols.append(Sym(id: id, attrs: passthrough, body: body, width: parts[2], height: parts[3]))
}

let required = ["nr-jar", "nr-jar-smart", "nr-jar-pickle", "nr-seal", "nr-lip", "nr-drip", "nr-sink"]
let found = symbols.map(\.id)
if found != required {
    fail("symbols.svg must define exactly manifest §7, in order: \(required.joined(separator: ", ")) — found: \(found.joined(separator: ", "))")
}

// MARK: - Naming: nr-jar-smart → jarSmart

func caseName(_ id: String) -> String {
    let parts = id.split(separator: "-").dropFirst().map(String.init)   // drop "nr"
    return parts.enumerated().map { i, p in i == 0 ? p : p.prefix(1).uppercased() + p.dropFirst() }.joined()
}

/// Wrap symbol content in a standalone SVG. `currentColor` has no meaning outside a
/// document, so it becomes black; the template renderer only reads alpha anyway.
func standalone(_ s: Sym) -> String {
    let body = s.body.replacingOccurrences(of: "currentColor", with: "#000000")
        .trimmingCharacters(in: .whitespacesAndNewlines)
    return "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"\(Int(s.width))\" height=\"\(Int(s.height))\" \(s.attrs)>\n\(body)\n</svg>"
}

func rawLiteral(_ s: String) -> String {
    // A raw multi-line string; the SVGs contain quotes and backslashes are absent, but raw is safest.
    guard !s.contains("\"\"\"#") else { fail("SVG contains the raw-string terminator") }
    return "#\"\"\"\n\(s)\n\"\"\"#"
}

// MARK: - Emit

var out = ""
func line(_ s: String = "") { out += s + "\n" }

line("// GENERATED by scripts/gen-symbols.swift from design/symbols.svg, design/logo.svg, design/logo-cog.svg — DO NOT EDIT.")
line("// Regenerate:  swift scripts/gen-symbols.swift design/symbols.svg design/logo.svg design/logo-cog.svg > Sources/UI/Symbols.swift")
line("// CI fails if this file differs from a fresh run. Change the SVGs, not this file.")
line()
line("import AppKit")
line("import SwiftUI")
line()
line("/// The seven symbols of manifest §7. Template images: colour comes from the caller.")
line("public enum NRSymbol: String, CaseIterable, Sendable {")
for s in symbols { line("    case \(caseName(s.id)) = \"\(s.id)\"") }
line()
line("    /// The symbol as a template `NSImage`, sized to its viewBox in points.")
line("    @MainActor public var nsImage: NSImage { NRSymbolStore.image(for: self) }")
line()
line("    /// The symbol as a SwiftUI `Image`, rendered as a template. Tint with `.foregroundStyle(_:)`.")
line("    @MainActor public var image: Image { Image(nsImage: nsImage).renderingMode(.template) }")
line()
line("    /// The standalone SVG document this symbol was embedded as.")
line("    public var svg: String {")
line("        switch self {")
for s in symbols {
    line("        case .\(caseName(s.id)):")
    line("            return \(rawLiteral(standalone(s)).replacingOccurrences(of: "\n", with: "\n            "))")
}
line("        }")
line("    }")
line("}")
line()
line("/// The mark (`logo.svg`) and the cog (`logo-cog.svg`), manifest §2. Full colour, never templates.")
line("public enum NRLogo: CaseIterable, Sendable {")
line("    /// `logo.svg` — app icon, titlebar, About. Minimum 16pt.")
line("    case mark")
line("    /// `logo-cog.svg` — site, onboarding, empty states, About window. Minimum 40pt.")
line("    case cog")
line()
line("    @MainActor public var nsImage: NSImage { NRSymbolStore.image(for: self) }")
line("    @MainActor public var image: Image { Image(nsImage: nsImage).renderingMode(.original) }")
line()
line("    /// The SVG file, byte for byte.")
line("    public var svg: String {")
line("        switch self {")
line("        case .mark:")
line("            return \(rawLiteral(logoSVG).replacingOccurrences(of: "\n", with: "\n            "))")
line("        case .cog:")
line("            return \(rawLiteral(cogSVG).replacingOccurrences(of: "\n", with: "\n            "))")
line("        }")
line("    }")
line("}")
line()
line("// MARK: - Loader (generated once, not a symbol)")
line()
line("/// Decodes each SVG once and caches the `NSImage`. Main-actor because `NSImage` is not Sendable.")
line("@MainActor enum NRSymbolStore {")
line("    private static var symbols: [NRSymbol: NSImage] = [:]")
line("    private static var logos: [NRLogo: NSImage] = [:]")
line()
line("    static func image(for s: NRSymbol) -> NSImage {")
line("        if let i = symbols[s] { return i }")
line("        let i = decode(s.svg, name: s.rawValue)")
line("        i.isTemplate = true")
line("        symbols[s] = i")
line("        return i")
line("    }")
line()
line("    static func image(for l: NRLogo) -> NSImage {")
line("        if let i = logos[l] { return i }")
line("        let i = decode(l.svg, name: \"\\(l)\")")
line("        i.isTemplate = false")
line("        logos[l] = i")
line("        return i")
line("    }")
line()
line("    private static func decode(_ svg: String, name: String) -> NSImage {")
line("        guard let image = NSImage(data: Data(svg.utf8)) else {")
line("            preconditionFailure(\"NRSymbol: \\(name) failed to decode — the SVG in /design is not what the generator saw\")")
line("        }")
line("        image.setName(name)")
line("        return image")
line("    }")
line("}")

FileHandle.standardOutput.write(out.data(using: .utf8)!)
